Traceback (most recent call last):
  File "download_harvard.py", line 47, in <module>
    utils.write_entry(name, url, edge_path, node_path, G.is_directed(), G.is_multigraph(),
  File "/sfs/qumulo/qproject/biocomplexity/cines/y2020/net.science_datasets/download_scripts/graph_info_csv_helpers.py", line 97, in write_entry
    graph_metadata = pd.read_csv(csv_filepath, delimiter=',', header=0)
  File "/home/hlc5v/.conda/envs/network_crawler/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/hlc5v/.conda/envs/network_crawler/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/hlc5v/.conda/envs/network_crawler/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/hlc5v/.conda/envs/network_crawler/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/hlc5v/.conda/envs/network_crawler/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
