Traceback (most recent call last):
  File "download_harvard.py", line 31, in <module>
    zipped_fp = utils.get_zip_fp(query_result['url'])
  File "/sfs/qumulo/qproject/biocomplexity/cines/y2020/net.science_datasets/download_scripts/graph_info_csv_helpers.py", line 25, in get_zip_fp
    graph_zipped_fp = urllib.request.urlopen(url)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
